#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
source /etc/profile

[ -f /etc/mount_mmc_ext4_overlay.sh ] && {
    /etc/mount_mmc_ext4_overlay.sh start
}

for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

